/**
 * Indian medicine reference list — generics + common brand names
 * Used for autocomplete suggestions in the supplier bill form.
 *
 * Sources: CDSCO approved generics, NPPA price-controlled list, common
 * OTC/Rx names from Indian retail pharmacies.
 *
 * Each entry: "Generic Name Strength UnitType"
 * Brand names are noted in comments but the names here follow the style
 * Indian retailers actually write on their invoices.
 */
export const INDIAN_MEDICINE_NAMES: string[] = [
  // ─── Analgesics / Antipyretics ─────────────────────────────────────────────
  "Paracetamol 500mg Tab",
  "Paracetamol 650mg Tab",
  "Paracetamol 1000mg Tab",
  "Paracetamol 125mg/5ml Syp",
  "Paracetamol 250mg/5ml Syp",
  "Paracetamol 500mg/5ml Sol",
  "Paracetamol 150mg Inj",
  "Ibuprofen 200mg Tab",
  "Ibuprofen 400mg Tab",
  "Ibuprofen 600mg Tab",
  "Ibuprofen 100mg/5ml Susp",
  "Diclofenac 50mg Tab",
  "Diclofenac 75mg SR Tab",
  "Diclofenac 100mg SR Tab",
  "Diclofenac 25mg/ml Inj",
  "Aceclofenac 100mg Tab",
  "Aceclofenac 200mg SR Tab",
  "Nimesulide 100mg Tab",
  "Nimesulide 50mg/5ml Susp",
  "Mefenamic Acid 250mg Cap",
  "Mefenamic Acid 500mg Tab",
  "Tramadol 50mg Cap",
  "Tramadol 100mg SR Tab",
  "Tramadol 50mg/ml Inj",
  "Aspirin 75mg Tab",
  "Aspirin 150mg Tab",
  "Aspirin 325mg Tab",
  "Ketorolac 10mg Tab",
  "Ketorolac 30mg/ml Inj",
  "Piroxicam 20mg Cap",
  "Naproxen 250mg Tab",
  "Naproxen 500mg Tab",
  "Etoricoxib 60mg Tab",
  "Etoricoxib 90mg Tab",
  "Etoricoxib 120mg Tab",
  "Celecoxib 100mg Cap",
  "Celecoxib 200mg Cap",
  "Paracetamol + Ibuprofen Tab",
  "Paracetamol + Diclofenac Tab",
  "Paracetamol + Tramadol Tab",

  // ─── Antibiotics ────────────────────────────────────────────────────────────
  "Amoxicillin 250mg Cap",
  "Amoxicillin 500mg Cap",
  "Amoxicillin 125mg/5ml Susp",
  "Amoxicillin 250mg/5ml Susp",
  "Amoxicillin + Clavulanate 375mg Tab",
  "Amoxicillin + Clavulanate 625mg Tab",
  "Amoxicillin + Clavulanate 1.2g Inj",
  "Azithromycin 250mg Tab",
  "Azithromycin 500mg Tab",
  "Azithromycin 200mg/5ml Susp",
  "Ciprofloxacin 250mg Tab",
  "Ciprofloxacin 500mg Tab",
  "Ciprofloxacin 200mg/100ml IV Inf",
  "Levofloxacin 250mg Tab",
  "Levofloxacin 500mg Tab",
  "Levofloxacin 750mg Tab",
  "Levofloxacin 500mg/100ml IV Inf",
  "Ofloxacin 200mg Tab",
  "Ofloxacin 400mg Tab",
  "Norfloxacin 400mg Tab",
  "Doxycycline 100mg Cap",
  "Doxycycline 200mg Tab",
  "Tetracycline 250mg Cap",
  "Tetracycline 500mg Cap",
  "Metronidazole 200mg Tab",
  "Metronidazole 400mg Tab",
  "Metronidazole 500mg/100ml IV Inf",
  "Tinidazole 500mg Tab",
  "Secnidazole 1g Tab",
  "Cefixime 200mg Tab",
  "Cefixime 400mg Tab",
  "Cefixime 100mg/5ml Susp",
  "Cefpodoxime 100mg Tab",
  "Cefpodoxime 200mg Tab",
  "Cefuroxime 250mg Tab",
  "Cefuroxime 500mg Tab",
  "Ceftriaxone 250mg Inj",
  "Ceftriaxone 500mg Inj",
  "Ceftriaxone 1g Inj",
  "Ceftriaxone 2g Inj",
  "Cefotaxime 1g Inj",
  "Cefoperazone 1g Inj",
  "Cefoperazone + Sulbactam 1.5g Inj",
  "Clarithromycin 250mg Tab",
  "Clarithromycin 500mg Tab",
  "Erythromycin 250mg Tab",
  "Erythromycin 500mg Tab",
  "Cloxacillin 250mg Cap",
  "Cloxacillin 500mg Cap",
  "Ampicillin 250mg Cap",
  "Ampicillin 500mg Cap",
  "Ampicillin + Cloxacillin 250mg Cap",
  "Ampicillin + Cloxacillin 500mg Cap",
  "Piperacillin + Tazobactam 4.5g Inj",
  "Meropenem 500mg Inj",
  "Meropenem 1g Inj",
  "Imipenem + Cilastatin 500mg Inj",
  "Vancomycin 500mg Inj",
  "Linezolid 600mg Tab",
  "Linezolid 600mg/300ml IV Inf",
  "Clindamycin 150mg Cap",
  "Clindamycin 300mg Cap",
  "Co-trimoxazole 480mg Tab",
  "Co-trimoxazole 960mg Tab",

  // ─── Antifungals ────────────────────────────────────────────────────────────
  "Fluconazole 150mg Cap",
  "Fluconazole 50mg Cap",
  "Itraconazole 100mg Cap",
  "Itraconazole 200mg Cap",
  "Terbinafine 250mg Tab",
  "Clotrimazole 1% Cream",
  "Miconazole 2% Cream",
  "Ketoconazole 200mg Tab",
  "Ketoconazole 2% Shampoo",
  "Nystatin 100000 units Tab",
  "Voriconazole 200mg Tab",
  "Voriconazole 200mg Inj",

  // ─── Antivirals ─────────────────────────────────────────────────────────────
  "Acyclovir 200mg Tab",
  "Acyclovir 400mg Tab",
  "Acyclovir 800mg Tab",
  "Acyclovir 5% Cream",
  "Oseltamivir 75mg Cap",
  "Oseltamivir 30mg/5ml Susp",
  "Tenofovir 300mg Tab",
  "Lamivudine 150mg Tab",
  "Lamivudine 300mg Tab",
  "Zidovudine 300mg Tab",
  "Efavirenz 600mg Tab",
  "Lopinavir + Ritonavir 200mg/50mg Tab",
  "Sofosbuvir 400mg Tab",
  "Ribavirin 200mg Tab",

  // ─── Antihypertensives ──────────────────────────────────────────────────────
  "Amlodipine 2.5mg Tab",
  "Amlodipine 5mg Tab",
  "Amlodipine 10mg Tab",
  "Atenolol 25mg Tab",
  "Atenolol 50mg Tab",
  "Atenolol 100mg Tab",
  "Metoprolol 25mg Tab",
  "Metoprolol 50mg Tab",
  "Metoprolol 100mg Tab",
  "Metoprolol 50mg SR Tab",
  "Metoprolol 100mg SR Tab",
  "Bisoprolol 2.5mg Tab",
  "Bisoprolol 5mg Tab",
  "Bisoprolol 10mg Tab",
  "Carvedilol 3.125mg Tab",
  "Carvedilol 6.25mg Tab",
  "Carvedilol 12.5mg Tab",
  "Propranolol 10mg Tab",
  "Propranolol 40mg Tab",
  "Ramipril 1.25mg Tab",
  "Ramipril 2.5mg Tab",
  "Ramipril 5mg Tab",
  "Ramipril 10mg Tab",
  "Enalapril 2.5mg Tab",
  "Enalapril 5mg Tab",
  "Enalapril 10mg Tab",
  "Lisinopril 2.5mg Tab",
  "Lisinopril 5mg Tab",
  "Lisinopril 10mg Tab",
  "Perindopril 4mg Tab",
  "Perindopril 8mg Tab",
  "Telmisartan 20mg Tab",
  "Telmisartan 40mg Tab",
  "Telmisartan 80mg Tab",
  "Losartan 25mg Tab",
  "Losartan 50mg Tab",
  "Losartan 100mg Tab",
  "Olmesartan 10mg Tab",
  "Olmesartan 20mg Tab",
  "Olmesartan 40mg Tab",
  "Valsartan 40mg Tab",
  "Valsartan 80mg Tab",
  "Valsartan 160mg Tab",
  "Irbesartan 75mg Tab",
  "Irbesartan 150mg Tab",
  "Irbesartan 300mg Tab",
  "Nifedipine 10mg Tab",
  "Nifedipine 20mg SR Tab",
  "Nifedipine 30mg XR Tab",
  "Amlodipine + Atenolol Tab",
  "Amlodipine + Telmisartan Tab",
  "Telmisartan + Hydrochlorothiazide Tab",
  "Clonidine 0.1mg Tab",
  "Methyldopa 250mg Tab",
  "Hydralazine 25mg Tab",
  "Prazosin 1mg Tab",
  "Doxazosin 1mg Tab",
  "Furosemide 20mg Tab",
  "Furosemide 40mg Tab",
  "Furosemide 20mg/2ml Inj",
  "Hydrochlorothiazide 12.5mg Tab",
  "Hydrochlorothiazide 25mg Tab",
  "Spironolactone 25mg Tab",
  "Spironolactone 50mg Tab",
  "Indapamide 1.5mg SR Tab",
  "Indapamide 2.5mg Tab",

  // ─── Antidiabetics ──────────────────────────────────────────────────────────
  "Metformin 500mg Tab",
  "Metformin 850mg Tab",
  "Metformin 1000mg Tab",
  "Metformin 500mg SR Tab",
  "Metformin 1000mg SR Tab",
  "Glimepiride 1mg Tab",
  "Glimepiride 2mg Tab",
  "Glimepiride 4mg Tab",
  "Glibenclamide 2.5mg Tab",
  "Glibenclamide 5mg Tab",
  "Gliclazide 40mg Tab",
  "Gliclazide 80mg Tab",
  "Gliclazide 30mg MR Tab",
  "Gliclazide 60mg MR Tab",
  "Glipizide 5mg Tab",
  "Glipizide 10mg Tab",
  "Glimepiride + Metformin Tab",
  "Vildagliptin 50mg Tab",
  "Vildagliptin + Metformin Tab",
  "Sitagliptin 25mg Tab",
  "Sitagliptin 50mg Tab",
  "Sitagliptin 100mg Tab",
  "Sitagliptin + Metformin Tab",
  "Teneligliptin 20mg Tab",
  "Dapagliflozin 5mg Tab",
  "Dapagliflozin 10mg Tab",
  "Empagliflozin 10mg Tab",
  "Empagliflozin 25mg Tab",
  "Canagliflozin 100mg Tab",
  "Pioglitazone 15mg Tab",
  "Pioglitazone 30mg Tab",
  "Acarbose 25mg Tab",
  "Acarbose 50mg Tab",
  "Insulin Regular 100IU/ml Inj Vial",
  "Insulin NPH 100IU/ml Inj Vial",
  "Insulin Glargine 100IU/ml Inj Vial",
  "Insulin Lispro 100IU/ml Inj Vial",
  "Insulin Aspart 100IU/ml Inj Vial",
  "Insulin Mixtard 30/70 100IU/ml Inj Vial",
  "Liraglutide 1.2mg/0.2ml Inj",

  // ─── Lipid Lowering ─────────────────────────────────────────────────────────
  "Atorvastatin 5mg Tab",
  "Atorvastatin 10mg Tab",
  "Atorvastatin 20mg Tab",
  "Atorvastatin 40mg Tab",
  "Atorvastatin 80mg Tab",
  "Rosuvastatin 5mg Tab",
  "Rosuvastatin 10mg Tab",
  "Rosuvastatin 20mg Tab",
  "Rosuvastatin 40mg Tab",
  "Simvastatin 10mg Tab",
  "Simvastatin 20mg Tab",
  "Simvastatin 40mg Tab",
  "Fenofibrate 145mg Tab",
  "Fenofibrate 160mg Tab",
  "Gemfibrozil 300mg Cap",
  "Ezetimibe 10mg Tab",
  "Atorvastatin + Ezetimibe Tab",

  // ─── Cardiac ────────────────────────────────────────────────────────────────
  "Digoxin 0.25mg Tab",
  "Amiodarone 100mg Tab",
  "Amiodarone 200mg Tab",
  "Amiodarone 150mg/3ml Inj",
  "Nitroglycerin 0.5mg SL Tab",
  "Isosorbide Mononitrate 10mg Tab",
  "Isosorbide Mononitrate 20mg Tab",
  "Isosorbide Mononitrate 30mg SR Tab",
  "Isosorbide Dinitrate 5mg SL Tab",
  "Clopidogrel 75mg Tab",
  "Prasugrel 10mg Tab",
  "Ticagrelor 60mg Tab",
  "Ticagrelor 90mg Tab",
  "Warfarin 1mg Tab",
  "Warfarin 2mg Tab",
  "Warfarin 5mg Tab",
  "Rivaroxaban 10mg Tab",
  "Rivaroxaban 15mg Tab",
  "Rivaroxaban 20mg Tab",
  "Apixaban 2.5mg Tab",
  "Apixaban 5mg Tab",
  "Dabigatran 75mg Cap",
  "Dabigatran 110mg Cap",
  "Dabigatran 150mg Cap",
  "Heparin 5000IU/ml Inj",
  "Enoxaparin 40mg/0.4ml Inj",
  "Enoxaparin 60mg/0.6ml Inj",

  // ─── Respiratory ────────────────────────────────────────────────────────────
  "Salbutamol 2mg Tab",
  "Salbutamol 4mg Tab",
  "Salbutamol 2mg/5ml Syp",
  "Salbutamol 100mcg MDI",
  "Levosalbutamol 1mg/2.5ml Neb Sol",
  "Ipratropium 20mcg MDI",
  "Tiotropium 18mcg Cap Turbuhaler",
  "Formoterol 6mcg Cap Turbuhaler",
  "Salmeterol 25mcg MDI",
  "Budesonide 100mcg MDI",
  "Budesonide 200mcg MDI",
  "Budesonide 400mcg MDI",
  "Budesonide 0.5mg/2ml Neb Sol",
  "Fluticasone 50mcg MDI",
  "Fluticasone 125mcg MDI",
  "Fluticasone 250mcg MDI",
  "Salmeterol + Fluticasone MDI",
  "Formoterol + Budesonide MDI",
  "Montelukast 4mg Tab",
  "Montelukast 5mg Chew Tab",
  "Montelukast 10mg Tab",
  "Theophylline 100mg SR Tab",
  "Theophylline 200mg SR Tab",
  "Aminophylline 250mg/10ml Inj",
  "Prednisolone 5mg Tab",
  "Prednisolone 10mg Tab",
  "Prednisolone 20mg Tab",
  "Methylprednisolone 4mg Tab",
  "Methylprednisolone 8mg Tab",
  "Methylprednisolone 16mg Tab",
  "Deflazacort 6mg Tab",
  "Codeine 10mg Tab",
  "Dextromethorphan 10mg/5ml Syp",
  "Ambroxol 30mg Tab",
  "Bromhexine 8mg Tab",
  "Acetylcysteine 200mg Sachet",
  "Guaifenesin 100mg/5ml Syp",

  // ─── Antihistamines / Allergy ────────────────────────────────────────────────
  "Cetirizine 5mg Tab",
  "Cetirizine 10mg Tab",
  "Levocetirizine 2.5mg Tab",
  "Levocetirizine 5mg Tab",
  "Fexofenadine 120mg Tab",
  "Fexofenadine 180mg Tab",
  "Loratadine 10mg Tab",
  "Desloratadine 2.5mg Tab",
  "Desloratadine 5mg Tab",
  "Bilastine 20mg Tab",
  "Chlorpheniramine 4mg Tab",
  "Pheniramine 22.75mg/ml Inj",
  "Promethazine 10mg Tab",
  "Promethazine 25mg Tab",
  "Hydroxyzine 10mg Tab",
  "Hydroxyzine 25mg Tab",
  "Montair LC Tab",
  "Montelukast + Levocetirizine Tab",

  // ─── Gastrointestinal ───────────────────────────────────────────────────────
  "Omeprazole 10mg Cap",
  "Omeprazole 20mg Cap",
  "Omeprazole 40mg Cap",
  "Pantoprazole 20mg Tab",
  "Pantoprazole 40mg Tab",
  "Pantoprazole 40mg Inj",
  "Esomeprazole 20mg Tab",
  "Esomeprazole 40mg Tab",
  "Rabeprazole 10mg Tab",
  "Rabeprazole 20mg Tab",
  "Lansoprazole 15mg Cap",
  "Lansoprazole 30mg Cap",
  "Ranitidine 150mg Tab",
  "Famotidine 20mg Tab",
  "Famotidine 40mg Tab",
  "Domperidone 10mg Tab",
  "Domperidone 5mg/5ml Susp",
  "Metoclopramide 10mg Tab",
  "Metoclopramide 5mg/ml Inj",
  "Ondansetron 4mg Tab",
  "Ondansetron 8mg Tab",
  "Ondansetron 2mg/ml Inj",
  "Ondansetron 4mg MD Tab",
  "Granisetron 1mg Tab",
  "Granisetron 1mg/ml Inj",
  "Bisacodyl 5mg Tab",
  "Lactulose 3.35g/5ml Sol",
  "Polyethylene Glycol 17g Sachet",
  "Ispaghula Husk Sachet",
  "Sorbitol 70% Sol",
  "Loperamide 2mg Cap",
  "Racecadotril 100mg Cap",
  "Rifaximin 200mg Tab",
  "Rifaximin 400mg Tab",
  "Zinc Sulphate 20mg Tab",
  "ORS Sachet",
  "Sucralfate 500mg Tab",
  "Sucralfate 1g/5ml Susp",
  "Antacid Susp",
  "Simethicone 40mg Tab",
  "Hyoscine 10mg Tab",
  "Dicyclomine 10mg Tab",
  "Mebeverine 135mg Tab",
  "Ursodeoxycholic Acid 150mg Tab",
  "Ursodeoxycholic Acid 300mg Tab",
  "Mesalamine 400mg Tab",
  "Mesalamine 800mg Tab",
  "Prednisolone 20mg Enema",

  // ─── Vitamins & Supplements ─────────────────────────────────────────────────
  "Vitamin B12 1500mcg Tab",
  "Vitamin B12 1000mcg Inj",
  "Vitamin B Complex Tab",
  "Vitamin C 500mg Tab",
  "Vitamin D3 1000IU Tab",
  "Vitamin D3 2000IU Tab",
  "Vitamin D3 60000IU Cap",
  "Vitamin D3 300000IU Inj",
  "Vitamin E 400IU Cap",
  "Calcium 500mg Tab",
  "Calcium + Vitamin D3 Tab",
  "Zinc 20mg Tab",
  "Iron 100mg Tab",
  "Ferrous Sulphate 200mg Tab",
  "Iron + Folic Acid Tab",
  "Folic Acid 5mg Tab",
  "Folic Acid 1mg Tab",
  "Multivitamin Tab",
  "Multimineral Tab",
  "Fish Oil 1000mg Cap",
  "Omega-3 1000mg Cap",
  "Biotin 10mg Tab",
  "Methylcobalamin 500mcg Tab",
  "Methylcobalamin + Alpha Lipoic Acid Tab",
  "Niacinamide 20mg Tab",
  "Pyridoxine 10mg Tab",
  "Thiamine 100mg Tab",

  // ─── Neurological / Psychiatric ─────────────────────────────────────────────
  "Gabapentin 100mg Cap",
  "Gabapentin 300mg Cap",
  "Gabapentin 400mg Cap",
  "Pregabalin 75mg Cap",
  "Pregabalin 150mg Cap",
  "Pregabalin 300mg Cap",
  "Carbamazepine 100mg Tab",
  "Carbamazepine 200mg Tab",
  "Carbamazepine 400mg Tab",
  "Phenytoin 100mg Tab",
  "Phenytoin 50mg/ml Inj",
  "Valproate 200mg Tab",
  "Valproate 500mg EC Tab",
  "Valproate 500mg CR Tab",
  "Levetiracetam 250mg Tab",
  "Levetiracetam 500mg Tab",
  "Levetiracetam 1000mg Tab",
  "Clonazepam 0.25mg Tab",
  "Clonazepam 0.5mg Tab",
  "Clonazepam 1mg Tab",
  "Diazepam 2mg Tab",
  "Diazepam 5mg Tab",
  "Diazepam 10mg/2ml Inj",
  "Alprazolam 0.25mg Tab",
  "Alprazolam 0.5mg Tab",
  "Lorazepam 1mg Tab",
  "Lorazepam 2mg Tab",
  "Midazolam 1mg/ml Inj",
  "Zolpidem 5mg Tab",
  "Zolpidem 10mg Tab",
  "Amitriptyline 10mg Tab",
  "Amitriptyline 25mg Tab",
  "Amitriptyline 75mg Tab",
  "Escitalopram 5mg Tab",
  "Escitalopram 10mg Tab",
  "Escitalopram 20mg Tab",
  "Sertraline 25mg Tab",
  "Sertraline 50mg Tab",
  "Sertraline 100mg Tab",
  "Fluoxetine 10mg Cap",
  "Fluoxetine 20mg Cap",
  "Paroxetine 10mg Tab",
  "Paroxetine 20mg Tab",
  "Venlafaxine 37.5mg Cap",
  "Venlafaxine 75mg XR Cap",
  "Venlafaxine 150mg XR Cap",
  "Mirtazapine 7.5mg Tab",
  "Mirtazapine 15mg Tab",
  "Duloxetine 20mg Cap",
  "Duloxetine 30mg Cap",
  "Duloxetine 60mg Cap",
  "Haloperidol 1.5mg Tab",
  "Haloperidol 5mg Tab",
  "Haloperidol 5mg/ml Inj",
  "Olanzapine 2.5mg Tab",
  "Olanzapine 5mg Tab",
  "Olanzapine 10mg Tab",
  "Risperidone 0.5mg Tab",
  "Risperidone 1mg Tab",
  "Risperidone 2mg Tab",
  "Quetiapine 25mg Tab",
  "Quetiapine 100mg Tab",
  "Quetiapine 200mg Tab",
  "Quetiapine 300mg SR Tab",
  "Aripiprazole 5mg Tab",
  "Aripiprazole 10mg Tab",
  "Aripiprazole 15mg Tab",
  "Lithium Carbonate 300mg Tab",
  "Donepezil 5mg Tab",
  "Donepezil 10mg Tab",
  "Memantine 5mg Tab",
  "Memantine 10mg Tab",
  "Pramipexole 0.125mg Tab",
  "Pramipexole 0.25mg Tab",
  "Levodopa + Carbidopa 100/10mg Tab",
  "Levodopa + Carbidopa 250/25mg Tab",
  "Trihexyphenidyl 2mg Tab",
  "Baclofen 10mg Tab",
  "Tizanidine 2mg Tab",
  "Tizanidine 4mg Tab",
  "Sumatriptan 50mg Tab",
  "Sumatriptan 100mg Tab",
  "Rizatriptan 5mg MD Tab",
  "Rizatriptan 10mg MD Tab",

  // ─── Thyroid ────────────────────────────────────────────────────────────────
  "Levothyroxine 12.5mcg Tab",
  "Levothyroxine 25mcg Tab",
  "Levothyroxine 50mcg Tab",
  "Levothyroxine 75mcg Tab",
  "Levothyroxine 100mcg Tab",
  "Levothyroxine 125mcg Tab",
  "Levothyroxine 150mcg Tab",
  "Carbimazole 5mg Tab",
  "Carbimazole 10mg Tab",
  "Propylthiouracil 50mg Tab",

  // ─── Hormones / Steroids ─────────────────────────────────────────────────────
  "Dexamethasone 0.5mg Tab",
  "Dexamethasone 4mg Tab",
  "Dexamethasone 4mg/ml Inj",
  "Hydrocortisone 10mg Tab",
  "Hydrocortisone 100mg Inj",
  "Betamethasone 0.5mg Tab",
  "Betamethasone 4mg Inj",
  "Fludrocortisone 0.1mg Tab",
  "Testosterone 25mg Gel",
  "Testosterone 250mg Inj",
  "Progesterone 100mg Cap",
  "Progesterone 200mg Cap",
  "Estradiol 1mg Tab",
  "Estradiol 2mg Tab",
  "Norethisterone 5mg Tab",
  "Medroxyprogesterone 2.5mg Tab",
  "Medroxyprogesterone 10mg Tab",

  // ─── Ophthalmology ──────────────────────────────────────────────────────────
  "Timolol 0.5% Eye Drops",
  "Latanoprost 0.005% Eye Drops",
  "Bimatoprost 0.03% Eye Drops",
  "Travoprost 0.004% Eye Drops",
  "Tobramycin 0.3% Eye Drops",
  "Moxifloxacin 0.5% Eye Drops",
  "Ciprofloxacin 0.3% Eye Drops",
  "Ofloxacin 0.3% Eye Drops",
  "Prednisolone 1% Eye Drops",
  "Dexamethasone 0.1% Eye Drops",
  "Ketorolac 0.5% Eye Drops",
  "Nepafenac 0.1% Eye Drops",
  "Carboxymethylcellulose 0.5% Eye Drops",
  "Hypromellose 0.3% Eye Drops",
  "Hydroxypropyl Methylcellulose Eye Drops",
  "Sodium Hyaluronate 0.1% Eye Drops",
  "Cyclopentolate 1% Eye Drops",
  "Atropine 1% Eye Drops",

  // ─── Dermatology ────────────────────────────────────────────────────────────
  "Betamethasone 0.1% Cream",
  "Betamethasone + Clotrimazole Cream",
  "Betamethasone + Gentamicin Cream",
  "Clobetasol 0.05% Cream",
  "Hydrocortisone 1% Cream",
  "Mometasone 0.1% Cream",
  "Fluocinolone 0.025% Cream",
  "Tacrolimus 0.03% Oint",
  "Tacrolimus 0.1% Oint",
  "Pimecrolimus 1% Cream",
  "Mupirocin 2% Oint",
  "Fusidic Acid 2% Cream",
  "Povidone Iodine 5% Oint",
  "Silver Sulfadiazine 1% Cream",
  "Permethrin 5% Cream",
  "Benzyl Benzoate 25% Lotion",
  "Salicylic Acid 6% Gel",
  "Tretinoin 0.025% Cream",
  "Tretinoin 0.05% Cream",
  "Isotretinoin 10mg Cap",
  "Isotretinoin 20mg Cap",
  "Clindamycin 1% Gel",
  "Benzoyl Peroxide 2.5% Gel",
  "Calamine Lotion",
  "Lacto Calamine Lotion",
  "Sunscreen SPF 30 Lotion",
  "Sunscreen SPF 50 Cream",

  // ─── Urology ─────────────────────────────────────────────────────────────────
  "Tamsulosin 0.2mg Cap",
  "Tamsulosin 0.4mg Cap",
  "Alfuzosin 10mg SR Tab",
  "Sildenafil 25mg Tab",
  "Sildenafil 50mg Tab",
  "Sildenafil 100mg Tab",
  "Tadalafil 5mg Tab",
  "Tadalafil 10mg Tab",
  "Tadalafil 20mg Tab",
  "Finasteride 1mg Tab",
  "Finasteride 5mg Tab",
  "Dutasteride 0.5mg Cap",
  "Oxybutynin 2.5mg Tab",
  "Oxybutynin 5mg Tab",
  "Solifenacin 5mg Tab",
  "Solifenacin 10mg Tab",
  "Mirabegron 25mg Tab",
  "Mirabegron 50mg Tab",

  // ─── Anaesthetics / Emergency ────────────────────────────────────────────────
  "Adrenaline 1mg/ml Inj",
  "Atropine 0.6mg/ml Inj",
  "Dopamine 200mg/5ml Inj",
  "Dobutamine 250mg/20ml Inj",
  "Noradrenaline 4mg/4ml Inj",
  "Adenosine 6mg/2ml Inj",
  "Lignocaine 2% Inj",
  "Bupivacaine 0.5% Inj",
  "Morphine 10mg/ml Inj",
  "Fentanyl 50mcg/ml Inj",
  "Ketamine 500mg/10ml Inj",
  "Propofol 10mg/ml Inj",
  "Naloxone 0.4mg/ml Inj",
  "Flumazenil 0.5mg/5ml Inj",
  "Dextrose 5% IV Inf",
  "Dextrose 25% IV Inf",
  "Normal Saline 0.9% IV Inf",
  "Ringer Lactate IV Inf",
  "DNS IV Inf",
  "Mannitol 20% IV Inf",
  "Potassium Chloride 15% Inj",
  "Calcium Gluconate 10% Inj",
  "Magnesium Sulphate 50% Inj",
  "Sodium Bicarbonate 7.5% Inj",

  // ─── Antituberculosis ────────────────────────────────────────────────────────
  "Isoniazid 100mg Tab",
  "Isoniazid 300mg Tab",
  "Rifampicin 150mg Cap",
  "Rifampicin 300mg Cap",
  "Rifampicin 450mg Cap",
  "Rifampicin 600mg Cap",
  "Pyrazinamide 500mg Tab",
  "Ethambutol 400mg Tab",
  "Ethambutol 800mg Tab",
  "Streptomycin 1g Inj",
  "Rifampicin + Isoniazid Tab",
  "Rifampicin + Isoniazid + Pyrazinamide Tab",

  // ─── Antimalarials ───────────────────────────────────────────────────────────
  "Hydroxychloroquine 200mg Tab",
  "Chloroquine 150mg Tab",
  "Chloroquine 250mg Tab",
  "Primaquine 2.5mg Tab",
  "Primaquine 7.5mg Tab",
  "Artemether 20mg + Lumefantrine 120mg Tab",
  "Quinine 300mg Tab",
  "Quinine 600mg/2ml Inj",

  // ─── IV Fluids / Nutrition ──────────────────────────────────────────────────
  "Human Albumin 20% IV Inf",
  "Human Albumin 25% IV Inf",
  "Amino Acid Solution IV Inf",
  "Lipid Emulsion 20% IV Inf",
  "Iron Sucrose 100mg/5ml Inj",
  "Ferric Carboxymaltose 500mg Inj",

  // ─── Vaccines ───────────────────────────────────────────────────────────────
  "Hepatitis B Vaccine Inj",
  "Influenza Vaccine Inj",
  "Pneumococcal Vaccine Inj",
  "Typhoid Vaccine Inj",
  "Rabies Vaccine Inj",
  "Tetanus Toxoid Inj",
  "MMR Vaccine Inj",
  "Varicella Vaccine Inj",
];

/**
 * Fuzzy-search medicine names.
 * Returns up to `limit` matches ordered by relevance:
 *   1. Starts-with match (highest priority)
 *   2. Contains match
 *   3. All search words present anywhere in name
 */

/** Pre-normalized entry used by the search index. */
export interface MedicineSearchEntry {
  original: string;
  lower: string;
}

/**
 * Build a normalized search index from optional inventory names merged with the
 * built-in medicine list.  Callers should memoize this (e.g. with `useMemo`)
 * and pass the result to `searchMedicineNames` so the O(n) normalization work
 * is only done when `inventoryNames` actually changes, not on every keystroke.
 */
export function buildMedicineSearchIndex(inventoryNames: string[] = []): MedicineSearchEntry[] {
  const merged = Array.from(new Set([...inventoryNames, ...INDIAN_MEDICINE_NAMES]));
  return merged.map(name => ({ original: name, lower: name.toLowerCase() }));
}

export function searchMedicineNames(
  query: string,
  inventoryNames: string[] = [],
  limit = 10,
  /** Pass a pre-built index from {@link buildMedicineSearchIndex} to avoid
   *  rebuilding the normalized list on every keystroke. */
  index?: MedicineSearchEntry[]
): string[] {
  const q = query.trim().toLowerCase();
  if (!q || q.length < 2) return [];

  const entries = index ?? buildMedicineSearchIndex(inventoryNames);

  const words = q.split(/\s+/);

  const tier1: string[] = []; // starts with query
  const tier2: string[] = []; // contains query as substring
  const tier3: string[] = []; // all words found in name

  for (const { original, lower } of entries) {
    if (lower.startsWith(q)) {
      tier1.push(original);
    } else if (lower.includes(q)) {
      tier2.push(original);
    } else if (words.every(w => lower.includes(w))) {
      tier3.push(original);
    }
  }

  return [...tier1, ...tier2, ...tier3].slice(0, limit);
}
